### PR TITLE
epic notifications

### PR DESCRIPTION
**Pull request by BronzW**
I haven't been able to test some safety features myself as I wasn't able to create another account locally so I don't know if the feature that checks if you are the person who owns the notification so only you can mark it as read so it would be really nice if anybody was willing to checkout this pr with the github cli would be very epic thank you

### CODE REVIEW

**Comment by BronzW** [comment]
Also should I keep the GetNotifications resolver or should I add a field resolver for user?

**Review by HenryLeC — APPROVED** [review]
Looks great ty

**Comment by HenryLeC** [comment]
> Also should I keep the GetNotifications resolver or should I add a field resolver for user?

I would leave it as a query

**Comment by BronzW** [comment]
> Looks great ty

ty

**Review by Angshu31 — COMMENTED** [review]
Looks fine to me

**Pull request merged**
