### PR TITLE
fix: safari flex gap

### PR DESCRIPTION
**Pull request by Simplyalex99**
Adjusted gap-12 property with gap-8 and added space-x-2 property which is supported on multiple browsers.

### CODE REVIEW

**Review by HenryLeC — APPROVED** [review]
Looks good ty

**Comment by HenryLeC** [comment]
I mill merge once @heybereket reviews

**Review by heybereket — APPROVED** [review]

**Review by BronzW — APPROVED** [review]

**Review by alexover1 — COMMENTED** [review]
Why are you using gap-8 _and_ space-x-2? If gap-8 doesn't work on all browsers why not just use like a bigger space-x?

**Comment by Simplyalex99** [comment]
Hey alexover1, yes you are correct. I thought I leave the gap property so that for chrome and browsers that do support it, it will be more spacious. But that can be changed and will work just as fine too.

**Pull request closed without merging**
