### PR TITLE
feat(web): add resort header

### PR DESCRIPTION
**Pull request by akashrajum7**

### CODE REVIEW

**Comment by HenryLeC** [comment]
Can you comment with a screenshot of what it looks like please

**Comment by HenryLeC** [comment]
@heybereket dont merge until @f1shy-dev approves

**Comment by akashrajum7** [comment]
Yes @HenryLeC , here you go - 
image

**Comment by f1shy-dev** [comment]
I will review right now once I get the environment setup

**Comment by HenryLeC** [comment]
Yep looks great, if you don't mind can you gitignore the custom css file that you made for vsc

**Review by f1shy-dev — APPROVED** [review]
seems good!

only things left to-do on this are:

- loading the data dynamically
- make the avatargroup based on an array of users, not fixed images

also @HenryLeC the `.vscode` thing is meant to not be ignored, it basically tells vscode that `@<whatever>` is an actual directive as tailwind directives give errors in vscode syntax highlighting.


can you make it dynamic (@akashrajum7)? If not i can do it.

**Comment by HenryLeC** [comment]
I can do all the data loading rn

**Comment by f1shy-dev** [comment]
sure, could you do that? i mean we already have the `data` there, just needs to be passed into the header.

**Comment by HenryLeC** [comment]
> also @HenryLeC the `.vscode` thing is meant to not be ignored, it basically tells vscode that `@<whatever>` is an actual directive as tailwind directives give errors in vscode syntax highlighting.

Ok cool makes sense

**Review by BronzW — APPROVED** [review]
As somebody who've used tailwind a total of 13 times in my life I approve

**Comment by HenryLeC** [comment]
> sure, could you do that? i mean we already have the `data` there, just needs to be passed into the header.

Yep okay I'm merging

**Comment by f1shy-dev** [comment]
@akashrajum7 we can add the vscode config as well as some other editor config in a new pr, if you could open it thatd be great

**Review by HenryLeC — APPROVED** [review]

**Comment by f1shy-dev** [comment]
should we merge then push the data loading after?

**Comment by f1shy-dev** [comment]
ok that works

**Comment by akashrajum7** [comment]
Oops, I removed the custom config :sweat: , should I add it back? Also @f1shy-dev I'd be happy to work on the data part as well, sure.

**Comment by HenryLeC** [comment]
> Oops, I removed the custom config :sweat: , should I add it back? Also @f1shy-dev I'd be happy to work on the data part as well, sure.

I merged just make a new pr with the config and I will handle the data stuff

**Comment by akashrajum7** [comment]
> @akashrajum7 we can add the vscode config as well as some other editor config in a new pr, if you could open it thatd be great

Sure, doing it.

**Comment by f1shy-dev** [comment]
Pretty sure @HenryLeC said he is going to be working on the data part.

> > Oops, I removed the custom config 😓 , should I add it back? Also @f1shy-dev I'd be happy to work on the data part as well, sure.
> 
> I merged just make a new pr with the config and I will handle the data stuff

**Comment by f1shy-dev** [comment]
replied to wrong one*

**Comment by akashrajum7** [comment]
Okay sure, I will open a PR for the config.

**Comment by f1shy-dev** [comment]
ok lets stop commenting here, and move to the other config pr while henry does config. Settled

**Pull request merged**
