### PR TITLE
Add Gitpod support + markdownlint config

### PR DESCRIPTION
**Pull request by ajhalili2006**
## Summary

* Add Markdownlint config
* Update the docs regarding Gitpod stuff
* Add Gitpod config
* And of course, add me to the list of contributors.

### CODE REVIEW

**Comment by f1shy-dev** [comment]
I was re-writing the docs anyway, should I merge that into this so there isn't any conflicts?

**Comment by ajhalili2006** [comment]
> I was re-writing the docs anyway, should I merge that into this so there isn't any conflicts?

Sure! I'll do that later.

**Comment by ajhalili2006** [comment]
Since the docs got an refresh, I might need to squash some conflicts chaos first.

**Comment by heybereket** [comment]
There have been a lot of changes in the repository after this pull request was made, make sure to pull the latest changes.

**Comment by f1shy-dev** [comment]
Any update on this?

**Comment by ajhalili2006** [comment]
@f1shy-dev @heybereket Did you nuked All Contributors stuff?

Screenshot_2021-05-01-11-05-55

**Comment by f1shy-dev** [comment]
Yeah I'm pretty sure we did

**Comment by HenryLeC** [comment]
Hey, sorry to do this to you but I am going to need to close this or. We just underwent a massive migration and are updating all the docs. If you would like to make a new or with updated docs we would greatly appreciate it

**Pull request closed without merging**
