### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by imabook**
**Description:**
Rewrote a nonsensical line in the spanish translation

### CODE REVIEW

**Comment by heybereket** [comment]
Thanks for submitting the PR to fix this issue. However, there are some conflicting files, take a look at it and after that's solved, I'll go ahead and merge! 👍🏽

**Comment by imabook** [comment]
> Thanks for submitting the PR to fix this issue. However, there are some conflicting files, take a look at it and after that's solved, I'll go ahead and merge! 👍🏽

I'm a bit lost sorry, a lot of stuff changed in the repo and the folder where i made the changes got deleted.
Should I make it again and place all of the translations then push or what?

Sorry for bothering, I'm pretty new to all of this stuff

**Comment by heybereket** [comment]
No problem! I see, yeah the issue is we're redoing the translations, so for now we aren't accepting any but we will be very soon, just not at the moment. I'll keep the PR open for when we do if you want to change things then, so I can merge.

The merge conflicts exist due to the files not existing anymore as we deleted them.

**Comment by imabook** [comment]
ah ok ok, thanks mate

**Comment by samarmohan** [comment]
Since your PR only changed one line, remember where that was and what you did. Reset all your changes and pull in the main repo. 

Note: Don’t PR the prod branch, only staging

**Comment by HenryLeC** [comment]
You can't make a pr to the oasis-sh:prod branch, if you could remake this pull request on the staging branch then I can get this merged for you.

**Comment by samarmohan** [comment]
Once you fix the conflicts, I'll merge. Can't really say no to a translation pr.

**Comment by HenryLeC** [comment]
I will fix this when translations get added back in. @heybereket Do we have a time on that?

**Comment by heybereket** [comment]
> I will fix this when translations get added back in. @heybereket Do we have a time on that?

Soon enough. I removed them as of today but they will be added back definitely before we release (most likely).

**Pull request closed without merging**
